### ISSUE TITLE
[Error] TfTypeError: Expected BIP32Path, got String "m/44'/\b'/0'/0/0"

### ISSUE THREAD

**Issue by kopeboy** [terra-money/feather.js#44]
I'm trying to derive a series of accounts from my mnemonic like this:

```js
/**
  * Generates subaccounts from a seed on a cosmos-sdk-compatible chain,
  * (secp256k1 ashing algorithm and bech32 address format with $chain prefix).
  * Call this from the current directory with arguments:
  * 0: @param {string} node for calling node.js
  * 1: @param {string} this_file_name for calling functions in this file
  * 2: @param {string} seed the mnemonic secret phrase of the root account
  * 3: @param {int} coin_type the coinType of the chain on which we generate sub-accounts
  * 4: @param {string} chain the address prefix of the chain on which we generate sub-accounts
  * 5: @param {int} from_id the index of the first sub-account to generate
  * 6: @param {int} to_id the index of the last sub-account to generate
  * ...to get (to_id - from_id) lines with the generated addresses in the console log
  */

import { MnemonicKey } from '@terra-money/feather.js';

for (let i = process.argv[5]; i <= process.argv[6]; i++) {
  const key = new MnemonicKey({
    mnemonic: process.argv[2], // optional, will be random if not provided
    coinType: process.argv[3], // optional, defaults to 330 for Terra, use 118 for most Cosmos chains
    account: 0, // optional, defaults to 0
    index: i, // optionally used for different sub-accounts, defaults to 0
  });
  console.log(key.accAddress(process.argv[4])); // provide chain prefix from github.com/cosmos/chain-registry
}
```

but when I run `node generate_accounts.js $seed 118 1 5` I get:

```
/featherjs/node_modules/typeforce/index.js:235
    throw new TfTypeError(surrogate || type, value)
          ^
TfTypeError: Expected BIP32Path, got String "m/44'/\b'/0'/0/0"
    at typeforce (/Users/kopeboy/ioc/wallets/featherjs/node_modules/typeforce/index.js:235:11)
    at BIP32.derivePath (/Users/kopeboy/ioc/wallets/featherjs/node_modules/bip32/src/bip32.js:171:9)
    at new MnemonicKey (/Users/kopeboy/ioc/wallets/featherjs/node_modules/@terra-money/feather.js/dist/key/MnemonicKey.js:103:33)
    at file:///Users/kopeboy/ioc/wallets/featherjs/generate_accounts.js:18:15
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  __type: [Function: BIP32Path],
  __value: "m/44'/\b'/0'/0/0",
  __valueTypeName: 'String'
}

Node.js v20.5.0
```

Is this a bug or am I doing something wrong? 🙏🏻

**Comment by emidev98** [comment]
Hey @kopeboy seems like you have a "m/44'/`\b`'/0'/0/0" (https://stackoverflow.com/questions/8657702/what-do-t-and-b-do) in the paath definition. Paths must look as follows: `m/44'/0'/0'/0/0`

**Comment by emidev98** [comment]
Hey @kopeboy I will proceed to close the issue due no response. Feel free to tagsomeone from the team or open a new one if there are any other queries or the issue was not solved by my previous suggestion
