### ISSUE TITLE
Integrate models for *gov.v1*

### ISSUE THREAD

**Issue by emidev98** [terra-money/feather.js#5]
CosmosSDK has released the new governance API. As soon as Terra Core is upgraded to the new version we should integrate the proto and amino models inside feather.js for gov.v1. 

This is an important dependency because will make the read workflow fail with the following error:

```
Error: not supported msg /cosmos.gov.v1.MsgDeposit
    at Object.fromData (/home/emi/GitHub/game-of-alliance/indexer/node_modules/@terra-money/feather.js/src/core/Msg.ts:421:15)
    at /home/emi/GitHub/game-of-alliance/indexer/node_modules/@terra-money/feather.js/src/core/Tx.ts:176:34
    at Array.map (<anonymous>)
    at Function.TxBody.fromData (/home/emi/GitHub/game-of-alliance/indexer/node_modules/@terra-money/feather.js/src/core/Tx.ts:176:21)
    at Function.Tx.fromData (/home/emi/GitHub/game-of-alliance/indexer/node_modules/@terra-money/feather.js/src/core/Tx.ts:51:14)
    at Function.TxInfo.fromData (/home/emi/GitHub/game-of-alliance/indexer/node_modules/@terra-money/feather.js/src/core/TxInfo.ts:61:10)
    at /home/emi/GitHub/game-of-alliance/indexer/node_modules/@terra-money/feather.js/src/client/lcd/api/TxAPI.ts:214:25
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

> /cosmos.gov.v1.MsgVote
> /cosmos.gov.v1.MsgDeposit

**Comment by emidev98** [comment]
Implemented here https://github.com/terra-money/feather.js/blob/main/src/client/lcd/api/GovV1API.ts
